# fly.toml app configuration file generated for rails-social on 2023-08-02T17:39:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rails-social"
primary_region = "waw"
console_command = "/rails/bin/rails console"

[[mounts]]
  source = "rails_social_data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
